import type { Metadata } from 'next'

import './globals.css'

// eslint-disable-next-line react-refresh/only-export-components
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />

        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <title>Bernas - Dev & Dsgn</title>
      </head>
      <body id="root">{children}</body>
    </html>
  )
}
